coverage:
  status:
    project: off
    patch:
      default:
        target: 90%
        informational: false
        if_not_found: success

comment:
  layout: condensed_header, diff, files
  require_changes: false
