packages:
  - apps/*
  - packages/*

allowBuilds:
  electron: true
  lefthook: true
  electron-winstaller: true
  esbuild: true
  '@swc/core': true
  '@fission-ai/openspec': false
  koffi: true
  workerd: false

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - knip@6.29.0
  - '@typescript-eslint/types@8.65.0'
  - baseline-browser-mapping@2.10.44
  - storybook@10.5.4
  - '@storybook/react-vite@10.5.4'
  - '@storybook/addon-a11y@10.5.4'
  - '@storybook/addon-vitest@10.5.4'
  - '@storybook/addon-themes@10.5.4'
  - '@storybook/addon-mcp@0.7.0'
  - '@storybook/builder-vite@10.5.4'
  - '@storybook/csf-plugin@10.5.4'
  - '@storybook/react-dom-shim@10.5.4'
  - '@storybook/react@10.5.4'

overrides:
  fast-check: 4.9.0
  'undici@>=7.0.0 <7.29.0': '^7.29.0'
  'js-yaml@>=4.0.0 <4.3.1': '^4.3.1'
  'nanoid@<3.3.18': '^3.3.18'

packageExtensions:
  '@lobehub/icons':
    peerDependenciesMeta:
      '@lobehub/ui':
        optional: true
